---
openapi: 3.0.3
info:
  title: Mojix ytem API
  contact:
    name: "Mojix, Inc."
    url: https://mojix.com
    email: support@mojix.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
security:
- JWT: []
tags:
- name: Supply chain
  description: API used to store and query list of tags or product/quantities
paths:
  /stock-management/manage/application/picking:
    get:
      tags:
      - Pick List
      responses:
        "200":
          description: OK
  /stock-management/manage/pick:
    post:
      tags:
      - Pick List
      parameters:
      - name: format
        in: query
        schema:
          type: string
      - name: from
        in: query
        schema:
          format: int32
          default: "0"
          type: integer
      - name: size
        in: query
        schema:
          format: int32
          type: integer
      - name: tenant
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /stock-management/manage/pick/transactions/{transactionId}:
    get:
      tags:
      - Pick List
      parameters:
      - name: transactionId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /stock-management/manage/pick/{id}:
    get:
      tags:
      - Pick List
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      - name: expirationTime
        in: query
        schema:
          type: string
      - name: format
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      - name: statusUpdatedByAsn
        in: query
        schema:
          default: false
          type: boolean
      responses:
        "200":
          description: OK
    delete:
      tags:
      - Pick List
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
  /stock-management/manage/{subprocess}:
    put:
      tags:
      - Pick List
      parameters:
      - name: subprocess
        in: path
        required: true
        schema:
          type: string
      - name: format
        in: query
        schema:
          default: quantity
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/application/status:
    get:
      tags:
      - Supply chain
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/process/crossreceive/{transaction_id}:
    post:
      tags:
      - Supply chain
      parameters:
      - name: transaction_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/process/crossship/{transaction_id}:
    post:
      tags:
      - Supply chain
      parameters:
      - name: transaction_id
        in: path
        required: true
        schema:
          type: string
      - name: destination
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/process/ship/{transaction_id}:
    post:
      tags:
      - Supply chain
      parameters:
      - name: transaction_id
        in: path
        required: true
        schema:
          type: string
      - name: destination
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/reference_lists:
    put:
      tags:
      - Supply chain
      parameters:
      - name: update_contents
        in: query
        schema:
          default: "true"
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/reference_lists/searches:
    post:
      tags:
      - Supply chain
      parameters:
      - name: format
        in: query
        schema:
          type: string
      - name: from
        in: query
        schema:
          format: int32
          default: "0"
          type: integer
      - name: size
        in: query
        schema:
          format: int32
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/reference_lists/searches/results:
    post:
      tags:
      - Supply chain
      parameters:
      - name: as_containers
        in: query
        schema:
          default: "false"
          type: boolean
      - name: format
        in: query
        schema:
          type: string
      - name: from
        in: query
        schema:
          format: int32
          default: "0"
          type: integer
      - name: result_format
        in: query
        schema:
          default: tag
          type: string
      - name: retrieveContents
        in: query
        schema:
          default: "true"
          type: boolean
      - name: size
        in: query
        schema:
          format: int32
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/reference_lists/searches/results/extended:
    post:
      tags:
      - Supply chain
      parameters:
      - name: format
        in: query
        schema:
          type: string
      - name: from
        in: query
        schema:
          format: int32
          default: "0"
          type: integer
      - name: size
        in: query
        schema:
          format: int32
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/reference_lists/{id}:
    delete:
      tags:
      - Supply chain
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/reference_lists/{list_id}:
    get:
      tags:
      - Supply chain
      parameters:
      - name: list_id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      - name: expiration_time
        in: query
        schema:
          type: string
      - name: format
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      - name: statusUpdatedByAsn
        in: query
        schema:
          default: false
          type: boolean
      responses:
        "200":
          description: OK
    put:
      tags:
      - Supply chain
      parameters:
      - name: list_id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/reference_lists/{list_id}/compare:
    get:
      tags:
      - Supply chain
      parameters:
      - name: list_id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      - name: as_quantity
        in: query
        schema:
          default: "false"
          type: boolean
      - name: as_sku_quantity
        in: query
        schema:
          default: "false"
          type: boolean
      - name: use_containers
        in: query
        schema:
          default: "false"
          type: boolean
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/transactions/{transaction_id}/results:
    get:
      tags:
      - Supply chain
      parameters:
      - name: transaction_id
        in: path
        required: true
        schema:
          type: string
      - name: bizstep
        in: query
        schema:
          type: string
      - name: format
        in: query
        schema:
          default: tag
          type: string
      responses:
        "200":
          description: OK
  /supply-chain-api/rest/supply_chain/transactions/{transaction_id}/results/extended:
    get:
      tags:
      - Supply chain
      parameters:
      - name: transaction_id
        in: path
        required: true
        schema:
          type: string
      - name: bizstep
        in: query
        schema:
          type: string
      - name: expiration_time
        in: query
        schema:
          type: string
      - name: format
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
